<?php

return [
    'ai' => [
        'base_url' => env('AI_BASE_URL'),
        'key' => env('AI_API_KEY'),
        'model' => env('AI_MODEL', 'gpt-5-mini'),
        'timeout' => (int) env('AI_TIMEOUT', 30),
        'provider_order' => array_values(array_filter(array_map('trim', explode(',', (string) env('AI_PROVIDER_ORDER', 'gemini,openai,groq,openrouter'))))),
        'providers' => [
            'gemini' => ['base_url' => env('GEMINI_BASE_URL', 'https://generativelanguage.googleapis.com/v1beta'), 'key' => env('GEMINI_API_KEY'), 'model' => env('GEMINI_MODEL', 'gemini-2.5-flash')],
            'openai' => ['base_url' => env('OPENAI_BASE_URL', 'https://api.openai.com/v1'), 'key' => env('OPENAI_API_KEY'), 'model' => env('OPENAI_MODEL', 'gpt-5-mini')],
            'groq' => ['base_url' => env('GROQ_BASE_URL', 'https://api.groq.com/openai/v1'), 'key' => env('GROQ_API_KEY'), 'model' => env('GROQ_MODEL', 'llama-3.3-70b-versatile')],
            'openrouter' => ['base_url' => env('OPENROUTER_BASE_URL', 'https://openrouter.ai/api/v1'), 'key' => env('OPENROUTER_API_KEY'), 'model' => env('OPENROUTER_MODEL', 'openai/gpt-4o-mini')],
        ],
    ],
    'postmark' => ['key' => env('POSTMARK_API_KEY')],
    'resend' => ['key' => env('RESEND_API_KEY')],
    'ses' => [
        'key' => env('AWS_ACCESS_KEY_ID'),
        'secret' => env('AWS_SECRET_ACCESS_KEY'),
        'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),
    ],
    'slack' => [
        'notifications' => [
            'bot_user_oauth_token' => env('SLACK_BOT_USER_OAUTH_TOKEN'),
            'channel' => env('SLACK_BOT_USER_DEFAULT_CHANNEL'),
        ],
    ],
    'paymob' => [
        'enabled' => (bool) env('PAYMOB_ENABLED', false),
        'base_url' => env('PAYMOB_BASE_URL', 'https://accept.paymob.com'),
        'secret_key' => env('PAYMOB_SECRET_KEY'),
        'public_key' => env('PAYMOB_PUBLIC_KEY'),
        'hmac_secret' => env('PAYMOB_HMAC_SECRET'),
        'integration_ids' => array_values(array_filter(array_map('intval', explode(',', (string) env('PAYMOB_INTEGRATION_IDS', ''))))),
        'notification_url' => env('PAYMOB_NOTIFICATION_URL'),
        'redirection_url' => env('PAYMOB_REDIRECTION_URL'),
        'timeout' => (int) env('PAYMOB_TIMEOUT', 15),
        'sandbox_probe_url' => env('PAYMOB_SANDBOX_PROBE_URL'),
    ],
    'kashier' => [
        'enabled' => (bool) env('KASHIER_ENABLED', false),
        'api_base_url' => env('KASHIER_API_BASE_URL', 'https://test-api.kashier.io'),
        'fep_base_url' => env('KASHIER_FEP_BASE_URL', 'https://test-fep.kashier.io'),
        'checkout_base_url' => env('KASHIER_CHECKOUT_BASE_URL', 'https://payments.kashier.io'),
        'merchant_id' => env('KASHIER_MERCHANT_ID'),
        'secret_key' => env('KASHIER_SECRET_KEY'),
        'payment_api_key' => env('KASHIER_PAYMENT_API_KEY'),
        'webhook_url' => env('KASHIER_WEBHOOK_URL'),
        'redirect_url' => env('KASHIER_REDIRECT_URL'),
        'timeout' => (int) env('KASHIER_TIMEOUT', 15),
        'sandbox_probe_url' => env('KASHIER_SANDBOX_PROBE_URL'),
    ],
    'social' => [
        'timeout' => (int) env('SOCIAL_HTTP_TIMEOUT', 15),
        'facebook' => ['verify_token' => env('SOCIAL_FACEBOOK_VERIFY_TOKEN'), 'send_url' => env('SOCIAL_FACEBOOK_SEND_URL'), 'comment_reply_url' => env('SOCIAL_FACEBOOK_COMMENT_REPLY_URL')],
        'instagram' => ['verify_token' => env('SOCIAL_INSTAGRAM_VERIFY_TOKEN'), 'send_url' => env('SOCIAL_INSTAGRAM_SEND_URL'), 'comment_reply_url' => env('SOCIAL_INSTAGRAM_COMMENT_REPLY_URL')],
        'whatsapp' => ['verify_token' => env('SOCIAL_WHATSAPP_VERIFY_TOKEN'), 'send_url' => env('SOCIAL_WHATSAPP_SEND_URL'), 'comment_reply_url' => env('SOCIAL_WHATSAPP_COMMENT_REPLY_URL')],
    ],
    'bosta' => [
        'enabled' => (bool) env('BOSTA_ENABLED', false),
        'base_url' => env('BOSTA_BASE_URL', 'https://app.bosta.co'),
        'api_key' => env('BOSTA_API_KEY'),
        'webhook_url' => env('BOSTA_WEBHOOK_URL'),
        'webhook_auth_header' => env('BOSTA_WEBHOOK_AUTH_HEADER', 'Authorization'),
        'webhook_auth_value' => env('BOSTA_WEBHOOK_AUTH_VALUE'),
        'timeout' => (int) env('BOSTA_TIMEOUT', 15),
    ],
];
