import Link from "next/link";
import type { Metric, Order } from "@/types/admin";

export function MetricCard({ metric }: { metric: Metric }) { return <div className="rounded-xl border border-[#dfe8df] bg-white p-3.5 shadow-[0_8px_24px_rgba(24,49,37,0.045)] transition hover:-translate-y-0.5 sm:rounded-2xl sm:p-5"><div className="flex items-center justify-between"><span className="grid size-8 place-items-center rounded-lg bg-[#edf5e9] text-sm font-semibold text-[#47715b] sm:size-9 sm:rounded-xl">{metric.icon === "revenue" ? "$" : metric.icon === "orders" ? "↗" : metric.icon === "customers" ? "♧" : "▦"}</span><span className={`rounded-full px-1.5 py-1 text-[9px] font-bold sm:px-2 sm:text-[10px] ${metric.trend === "up" ? "bg-[#edf7dc] text-[#608428]" : "bg-[#fff0eb] text-[#c96349]"}`}>{metric.change}</span></div><p className="mt-3 text-[11px] font-medium text-[#718178] sm:mt-5 sm:text-xs">{metric.label}</p><p className="mt-0.5 text-xl font-bold tracking-[-0.04em] text-[#193227] sm:mt-1 sm:text-2xl">{metric.value}</p></div>; }

export function SalesChart() { return <div className="rounded-2xl border border-[#dfe8df] bg-white p-4 shadow-[0_8px_24px_rgba(24,49,37,0.045)] sm:p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="font-bold tracking-tight">Sales overview</h2><p className="mt-1 text-[11px] text-[#8b9991] sm:text-xs">Revenue performance over the last 6 months</p></div><button className="shrink-0 rounded-lg border border-[#dfe7df] px-2.5 py-2 text-[10px] font-semibold text-[#52655a] sm:px-3 sm:text-xs">Last 6 months⌄</button></div><div className="mt-6 flex h-44 items-end gap-2 sm:mt-7 sm:h-52 sm:gap-6">{[42,58,48,72,66,84,78,91].map((height, index) => <div key={index} className="flex flex-1 flex-col items-center gap-2 sm:gap-3"><div className={`w-full rounded-t-md ${index === 7 ? "bg-[#cbe95d]" : "bg-[#dfeade]"}`} style={{ height: `${height}%` }} /><span className="text-[9px] text-[#95a29b] sm:text-[10px]">{["Apr","May","Jun","Jul","Aug","Sep","Oct","Nov"][index]}</span></div>)}</div></div>; }

export function OrdersTable({ orders }: { orders: Order[] }) { return <div className="rounded-2xl border border-[#e1e9e1] bg-white shadow-[0_5px_22px_rgba(24,49,37,0.035)]"><div className="flex items-center justify-between border-b border-[#edf1ed] p-5"><div><h2 className="font-bold">Recent orders</h2><p className="mt-1 text-xs text-[#8b9991]">Stay on top of your latest sales</p></div><Link href="/orders" className="text-xs font-bold text-[#608428] hover:underline">View all →</Link></div><div className="overflow-x-auto"><table className="w-full min-w-[580px] text-left text-xs"><thead className="bg-[#fafcf9] text-[10px] uppercase tracking-wider text-[#9aa79f]"><tr><th className="px-5 py-3 font-semibold">Order</th><th className="px-5 py-3 font-semibold">Customer</th><th className="px-5 py-3 font-semibold">Date</th><th className="px-5 py-3 font-semibold">Total</th><th className="px-5 py-3 font-semibold">Status</th></tr></thead><tbody>{orders.map((order) => <tr key={order.id} className="border-t border-[#edf1ed] text-[#4c5d54]"><td className="px-5 py-4 font-bold text-[#203a2d]">{order.id}</td><td className="px-5 py-4">{order.customer}</td><td className="px-5 py-4 text-[#8b9991]">{order.date}</td><td className="px-5 py-4 font-semibold">${order.total.toFixed(2)}</td><td className="px-5 py-4"><StatusBadge status={order.status} /></td></tr>)}</tbody></table></div></div>; }

export function StatusBadge({ status }: { status: string }) { const styles: Record<string, string> = { Completed: "bg-[#edf7dc] text-[#608428]", Processing: "bg-[#e7f2f5] text-[#367183]", Pending: "bg-[#fff4d9] text-[#aa7a20]", Cancelled: "bg-[#fff0eb] text-[#c96349]", Active: "bg-[#edf7dc] text-[#608428]", Draft: "bg-[#f0f2f0] text-[#738078]" }; return <span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-bold ${styles[status] ?? "bg-slate-100 text-slate-600"}`}>{status}</span>; }
