import { useEffect, useMemo, useState } from 'react'
import { MoreHorizontal, Package, Pencil, Plus, Search, Trash2 } from 'lucide-react'
import { ApiError, createProduct, deleteProduct, listProducts, updateProduct } from '../lib/api'
import type { ApiProduct } from '../lib/api'

type Props = { onToast: (message: string, type?: 'success' | 'error') => void }

type ProductForm = { name: string; description: string; type: 'simple' | 'variable'; status: string }
const emptyForm: ProductForm = { name: '', description: '', type: 'simple', status: 'active' }

export function CatalogPage({ onToast }: Props) {
  const [products, setProducts] = useState<ApiProduct[]>([])
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState('all')
  const [loading, setLoading] = useState(true)
  const [form, setForm] = useState<ProductForm>(emptyForm)
  const [editing, setEditing] = useState<ApiProduct | null>(null)
  const [formOpen, setFormOpen] = useState(false)
  const [saving, setSaving] = useState(false)
  const [deleteTarget, setDeleteTarget] = useState<ApiProduct | null>(null)

  const load = () => { setLoading(true); listProducts({ per_page: 100 }).then((data) => setProducts(Array.isArray(data) ? data : data.data ?? [])).catch((error: unknown) => onToast(error instanceof ApiError ? error.message : 'تعذر تحميل المنتجات', 'error')).finally(() => setLoading(false)) }
  // The initial fetch synchronizes the screen with the external Laravel API.
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { load() }, [])
  const visible = useMemo(() => products.filter((product) => (status === 'all' || product.status === status) && product.name.toLowerCase().includes(query.toLowerCase())), [products, query, status])
  const openCreate = () => { setEditing(null); setForm(emptyForm); setFormOpen(true) }
  const openEdit = (product: ApiProduct) => { setEditing(product); setForm({ name: product.name, description: '', type: 'simple', status: product.status ?? 'active' }); setFormOpen(true) }
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { if (editing) await updateProduct(editing.id, form); else await createProduct(form); onToast(editing ? 'تم تحديث المنتج' : 'تم إنشاء المنتج'); setEditing(null); setForm(emptyForm); setFormOpen(false); load() } catch (error) { onToast(error instanceof ApiError ? error.message : 'تعذر حفظ المنتج', 'error') } finally { setSaving(false) } }
  const remove = async () => { if (!deleteTarget) return; try { await deleteProduct(deleteTarget.id); setProducts((items) => items.filter((item) => item.id !== deleteTarget.id)); onToast('تم حذف المنتج'); setDeleteTarget(null) } catch (error) { onToast(error instanceof ApiError ? error.message : 'تعذر حذف المنتج', 'error') } }

  return <div className="screen-page"><ScreenHeader eyebrow="الكتالوج" title="المنتجات" description="إدارة المنتجات والأسعار والحالة من قاعدة بيانات المتجر." action={<button className="primary-button" onClick={openCreate}><Plus size={17} /> إضافة منتج</button>} /><div className="screen-toolbar"><label className="screen-search"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ابحث باسم المنتج..." /></label><div className="filter-chips"><button className={`filter-chip ${status === 'all' ? 'selected' : ''}`} onClick={() => setStatus('all')}>الكل</button>{['active', 'draft', 'archived'].map((value) => <button key={value} className={`filter-chip ${status === value ? 'selected' : ''}`} onClick={() => setStatus(value)}>{value === 'active' ? 'نشط' : value === 'draft' ? 'مسودة' : 'مؤرشف'}</button>)}</div></div><section className="data-card"><div className="table-wrap">{loading ? <SkeletonRows /> : visible.length === 0 ? <div className="empty-state"><Package size={28} /><b>لا توجد منتجات</b><span>أنشئ أول منتج لبدء إدارة الكتالوج.</span><button className="primary-button" onClick={openCreate}><Plus size={16} /> إضافة منتج</button></div> : <table><thead><tr><th>المنتج</th><th>التصنيف</th><th>السعر</th><th>الحالة</th><th>الإجراءات</th></tr></thead><tbody>{visible.map((product) => <tr key={product.id}><td><span className="customer"><span className="product-avatar"><Package size={16} /></span><b>{product.name}</b></span></td><td className="muted">{product.category?.name ?? 'بدون تصنيف'}</td><td><b>{product.price ?? 0} ر.س</b></td><td><span className={`status status-${product.status === 'active' ? 'تم-الشحن' : 'مكتمل'}`}><i />{product.status === 'active' ? 'نشط' : product.status === 'draft' ? 'مسودة' : 'مؤرشف'}</span></td><td><div className="quick-actions"><button title="تعديل" onClick={() => openEdit(product)}><Pencil size={16} /></button><button title="حذف" className="danger" onClick={() => setDeleteTarget(product)}><Trash2 size={16} /></button><button title="المزيد"><MoreHorizontal size={16} /></button></div></td></tr>)}</tbody></table>}</div><div className="table-footer"><span className="muted">عرض {visible.length} من {products.length} منتج</span></div></section>{formOpen && <ProductFormModal form={form} setForm={setForm} editing={editing} saving={saving} onClose={() => { setEditing(null); setForm(emptyForm); setFormOpen(false) }} onSubmit={save} />}{deleteTarget && <ConfirmDelete name={deleteTarget.name} onCancel={() => setDeleteTarget(null)} onConfirm={remove} />}</div>
}

function ScreenHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action: React.ReactNode }) { return <div className="screen-header"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="muted">{description}</p></div>{action}</div> }
function SkeletonRows() { return <div className="skeleton-table">{[1, 2, 3, 4, 5].map((row) => <div className="skeleton-row" key={row}><span /><span /><span /><span /></div>)}</div> }
function ProductFormModal({ form, setForm, editing, saving, onClose, onSubmit }: { form: ProductForm; setForm: React.Dispatch<React.SetStateAction<ProductForm>>; editing: ApiProduct | null; saving: boolean; onClose: () => void; onSubmit: (event: React.FormEvent) => void }) { return <div className="modal-backdrop" onClick={onClose}><div className="form-modal" onClick={(event) => event.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">الكتالوج</span><h2>{editing ? 'تعديل المنتج' : 'إضافة منتج'}</h2></div><button className="icon-button" onClick={onClose}>×</button></div><form onSubmit={onSubmit}><label className="form-field"><span>اسم المنتج *</span><input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="اسم المنتج" /></label><label className="form-field"><span>نوع المنتج</span><select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value as ProductForm['type'] })}><option value="simple">بسيط</option><option value="variable">متعدد الخيارات</option></select></label><label className="form-field"><span>الحالة</span><select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}><option value="active">نشط</option><option value="draft">مسودة</option><option value="archived">مؤرشف</option></select></label><label className="form-field"><span>الوصف</span><textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="وصف المنتج..." /></label><div className="modal-actions"><button type="button" className="outline-button" onClick={onClose}>إلغاء</button><button className="primary-button" disabled={saving}>{saving ? 'جار الحفظ...' : 'حفظ المنتج'}</button></div></form></div></div> }
function ConfirmDelete({ name, onCancel, onConfirm }: { name: string; onCancel: () => void; onConfirm: () => void }) { return <div className="modal-backdrop" onClick={onCancel}><div className="confirm-modal" onClick={(event) => event.stopPropagation()}><div className="danger-icon"><Trash2 size={20} /></div><h2>حذف المنتج؟</h2><p>سيتم حذف <b>{name}</b> من الكتالوج. لا يمكن التراجع عن هذا الإجراء.</p><div className="modal-actions"><button className="outline-button" onClick={onCancel}>إلغاء</button><button className="danger-button" onClick={onConfirm}>تأكيد الحذف</button></div></div></div> }
