import { ArrowDownLeft, ArrowUpLeft, CalendarDays, ChevronDown, CircleDollarSign, MoreHorizontal, ShoppingCart, Users } from 'lucide-react'

const stats = [{ label: 'إجمالي المبيعات', value: '٩٨٣,٤١٠ ر.س', change: '+٣.٣٤٪', icon: CircleDollarSign, tone: 'orange' }, { label: 'إجمالي الطلبات', value: '٥٨,٣٧٥', change: '-٢.٨٩٪', icon: ShoppingCart, tone: 'plain' }, { label: 'إجمالي الزيارات', value: '٢٣٧,٧٨٢', change: '+٨.٠٢٪', icon: Users, tone: 'plain' }]
const categories = [['الإلكترونيات', '١,٢٠٠,٠٠٠', 'orange'], ['الأزياء', '٩٥٠,٠٠٠', 'gold'], ['المنزل والمطبخ', '٧٥٠,٠٠٠', 'sand'], ['الجمال والعناية', '٥٠٠,٠٠٠', 'light']]
const countries = [['المملكة العربية السعودية', '٣٦٪', 82], ['الإمارات العربية المتحدة', '٢٤٪', 58], ['الكويت', '١٧.٥٪', 43], ['قطر', '١٥٪', 37]]

function Stats() { return <div className="stats-grid">{stats.map(({ label, value, change, icon: Icon, tone }) => <div className={`stat-card ${tone}`} key={label}><div className="stat-top"><span>{label}</span><Icon size={20} /></div><strong>{value}</strong><div className={`change ${change.startsWith('-') ? 'negative' : ''}`}>{change.startsWith('-') ? <ArrowDownLeft size={14} /> : <ArrowUpLeft size={14} />}{change}<small>مقارنة بالأسبوع الماضي</small></div></div>)}</div> }
function RevenueChart() { return <section className="panel revenue-panel"><div className="panel-head"><div><h2>تحليلات الإيرادات</h2><div className="legend"><span className="legend-line" /> الإيرادات <span className="legend-dashed" /> الطلبات</div></div><button className="select-button">آخر ٨ أيام <ChevronDown size={15} /></button></div><div className="chart"><div className="y-labels"><span>١٦ك</span><span>١٢ك</span><span>٨ك</span><span>٤ك</span><span>٠</span></div><div className="chart-area"><div className="grid-lines" /><svg viewBox="0 0 700 190" preserveAspectRatio="none"><path className="chart-line" d="M0 130 C55 82 80 118 130 122 S190 50 250 83 S330 82 375 42 S430 83 490 88 S535 130 580 80 S640 78 700 52" /><path className="chart-line dashed" d="M0 160 C60 195 78 115 135 130 S205 100 255 142 S330 125 375 93 S430 137 490 150 S535 185 580 130 S645 130 700 140" /></svg><div className="x-labels"><span>١٢ أغسطس</span><span>١٤ أغسطس</span><span>١٦ أغسطس</span><span>١٨ أغسطس</span><span>٢٠ أغسطس</span></div></div></div></section> }
function TargetCard() { return <section className="panel target-panel"><div className="panel-head"><h2>الهدف الشهري</h2><MoreHorizontal size={20} /></div><div className="gauge"><div className="gauge-inner"><strong>٨٥٪</strong><span>من الشهر الماضي</span></div></div><h3>تقدم رائع! 🎉</h3><p>زادت مبيعاتك بنسبة <b>٨.٠٢٪</b> عن الشهر الماضي</p><div className="target-values"><div><small>الهدف</small><b>٦٠٠,٠٠٠</b></div><div><small>الإيرادات</small><b>٥١٠,٠٠٠</b></div></div></section> }
function Categories() { return <section className="panel categories-panel"><div className="panel-head"><h2>أهم التصنيفات</h2><button className="link-button">عرض الكل</button></div><div className="donut"><div><strong>٣,٤٠٠,٠٠٠</strong><span>إجمالي المبيعات</span></div></div><div className="category-list">{categories.map(([name, value, tone]) => <div key={name}><span><i className={tone} />{name}</span><b>{value} ر.س</b></div>)}</div></section> }
function BottomPanels() { const conversion = [['مشاهدات المنتج', '٢٥,٠٠٠', '+٩٪'], ['إضافة للسلة', '١٢,٠٠٠', '+٦٪'], ['إتمام الدفع', '٨,٥٠٠', '+٤٪'], ['مشتريات مكتملة', '٦,٢٠٠', '+٧٪'], ['السلات المتروكة', '٣,٠٠٠', '-٥٪']] as const; return <><section className="panel users-panel"><div className="panel-head"><div><h2>المستخدمون النشطون</h2><strong className="big-number">٢,٧٥٨</strong><small>مستخدم</small></div><MoreHorizontal size={20} /></div><div className="user-change">+٨.٠٢٪ <small>من الشهر الماضي</small></div>{countries.map(([name, percent, width]) => <div className="country" key={name}><div><span>{name}</span><b>{percent}</b></div><div className="progress"><i style={{ width: `${width}%` }} /></div></div>)}</section><section className="conversion-section"><div className="conversion-heading"><h2>معدل التحويل</h2><button className="select-button">هذا الأسبوع <ChevronDown size={15} /></button></div><div className="conversion-card-grid">{conversion.map(([label, value, change], index) => <div className={`conversion-card ${index === 4 ? 'abandoned-card' : ''}`} key={label}><div className="conversion-card-top"><span>{label}</span><MoreHorizontal size={16} /></div><b>{value}</b><em className={index === 4 ? 'bad' : ''}>{change}</em><div className="conversion-bar" style={{ height: `${42 + index * 18}%` }} /></div>)}</div></section></> }

export function Dashboard() { return <div className="dashboard"><div className="page-heading"><div><h1>مرحباً محمد 👋</h1><p>إليك نظرة سريعة على أداء متجرك اليوم</p></div><button className="date-button"><CalendarDays size={17} /> ١٢ - ٢٠ أغسطس ٢٠٢٤ <ChevronDown size={15} /></button></div><Stats /><div className="dashboard-grid"><RevenueChart /><TargetCard /><Categories /><BottomPanels /></div></div> }
