import { useEffect, useState } from 'react'
import { RefreshCw, RotateCcw, Webhook } from 'lucide-react'
import { ApiError, listIntegrationEvents, retryIntegrationEvent } from '../lib/api'

type EventRow = { id: number; source: string; provider: string | null; event_id: string; event_type: string; status: string; reference: string | null; error: string | null; created_at: string }
type Props = { onToast: (message: string, type?: 'success' | 'error') => void }
const labels: Record<string, string> = { payment: 'الدفع', shipping: 'الشحن', social: 'التجارة الاجتماعية', received: 'مستلم', processed: 'تمت المعالجة', failed: 'فشل', retrying: 'قيد الإعادة' }
export function IntegrationsPage({ onToast }: Props) {
  const [rows, setRows] = useState<EventRow[]>([]); const [source, setSource] = useState(''); const [status, setStatus] = useState(''); const [loading, setLoading] = useState(true)
  const load = async () => { setLoading(true); try { setRows(await listIntegrationEvents({ source, status })) } catch (error) { onToast(error instanceof ApiError ? error.message : 'تعذر تحميل سجل التكاملات', 'error') } finally { setLoading(false) } }
  // Synchronize the selected filters with the external Laravel API.
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { void load() }, [source, status])
  const retry = async (row: EventRow) => { try { await retryIntegrationEvent(row.source, row.id); onToast('تمت جدولة إعادة المحاولة'); await load() } catch (error) { onToast(error instanceof ApiError ? error.message : 'تعذر إعادة المحاولة', 'error') } }
  return <div className="screen-page"><div className="screen-header"><div><p className="eyebrow">التشغيل / التكاملات</p><h1>سجل التكاملات والـWebhooks</h1><p className="muted">تابع استقبال أحداث الدفع والشحن والتجارة الاجتماعية وأعد المحاولة عند الحاجة.</p></div><button className="outline-button" onClick={() => void load()}><RefreshCw size={15} /> تحديث</button></div><div className="filter-bar"><select value={source} onChange={(event) => setSource(event.target.value)}><option value="">كل المصادر</option><option value="payment">الدفع</option><option value="shipping">الشحن</option><option value="social">التجارة الاجتماعية</option></select><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">كل الحالات</option><option value="received">مستلم</option><option value="failed">فشل</option><option value="retrying">قيد الإعادة</option><option value="processed">تمت المعالجة</option></select></div><section className="data-card"><div className="table-wrap">{loading ? <div className="skeleton-table">{[1, 2, 3].map((item) => <div className="skeleton-row" key={item}><span /><span /><span /><span /></div>)}</div> : rows.length === 0 ? <div className="empty-state"><Webhook size={28} /><b>لا توجد أحداث تكامل</b><span>ستظهر أحداث مزودي الدفع والشحن هنا عند استقبالها.</span></div> : <table><thead><tr><th>المصدر</th><th>المزوّد</th><th>نوع الحدث</th><th>المعرّف</th><th>الحالة</th><th>التاريخ</th><th>إجراء</th></tr></thead><tbody>{rows.map((row) => <tr key={`${row.source}-${row.id}`}><td>{labels[row.source] ?? row.source}</td><td>{row.provider ?? '—'}</td><td>{row.event_type}</td><td className="order-id">{row.event_id}</td><td><span className="status"><i />{labels[row.status] ?? row.status}</span></td><td className="muted">{row.created_at}</td><td>{['failed', 'error', 'received'].includes(row.status) && <button className="quick-action-button" title="إعادة المحاولة" onClick={() => void retry(row)}><RotateCcw size={15} /></button>}</td></tr>)}</tbody></table>}</div><div className="table-footer"><span className="muted">عرض {rows.length} حدثًا</span></div></section></div>
}
