import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, Boxes, Minus, Package, Plus, Search } from 'lucide-react'
import { ApiError, adjustInventory, listInventory } from '../lib/api'
import type { ApiInventory } from '../lib/api'

type Props = { onToast: (message: string, type?: 'success' | 'error') => void }
export function InventoryPage({ onToast }: Props) {
  const [items, setItems] = useState<ApiInventory[]>([])
  const [query, setQuery] = useState('')
  const [lowOnly, setLowOnly] = useState(false)
  const [loading, setLoading] = useState(true)
  const [selected, setSelected] = useState<ApiInventory | null>(null)
  const load = () => { setLoading(true); listInventory().then(setItems).catch((error: unknown) => onToast(error instanceof ApiError ? error.message : 'تعذر تحميل المخزون', 'error')).finally(() => setLoading(false)) }
  // The initial fetch synchronizes the screen with the external Laravel API.
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { load() }, [])
  const visible = useMemo(() => items.filter((item) => { const name = item.product?.name ?? `منتج #${item.product_id}`; const available = item.available ?? 0; return name.toLowerCase().includes(query.toLowerCase()) && (!lowOnly || available <= 5) }), [items, query, lowOnly])
  const adjust = async (quantity: number) => { if (!selected) return; try { await adjustInventory({ product_id: selected.product_id, quantity, reason: quantity > 0 ? 'purchase' : 'loss', note: 'تعديل من لوحة الإدارة' }); onToast('تم تحديث المخزون'); setSelected(null); load() } catch (error) { onToast(error instanceof ApiError ? error.message : 'تعذر تعديل المخزون', 'error') } }
  const available = items.reduce((sum, item) => sum + (item.available ?? 0), 0)
  const low = items.filter((item) => (item.available ?? 0) <= 5).length
  return <div className="screen-page"><div className="screen-header"><div><p className="eyebrow">العمليات</p><h1>المخزون</h1><p className="muted">راقب الكمية المتاحة والمحجوزة وعدّل المخزون بأمان.</p></div><div className="inventory-summary"><span><b>{available}</b> وحدة متاحة</span><span className={low ? 'warning-text' : ''}><b>{low}</b> منخفض المخزون</span></div></div><div className="screen-toolbar"><label className="screen-search"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ابحث عن منتج..." /></label><button className={`filter-chip ${lowOnly ? 'selected' : ''}`} onClick={() => setLowOnly(!lowOnly)}><AlertTriangle size={13} /> منخفض المخزون فقط</button></div><section className="data-card"><div className="table-wrap">{loading ? <SkeletonRows /> : visible.length === 0 ? <div className="empty-state"><Boxes size={28} /><b>لا توجد عناصر مخزون</b><span>لا توجد نتائج مطابقة.</span></div> : <table><thead><tr><th>المنتج</th><th>المتاح</th><th>المحجوز</th><th>الإجمالي</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{visible.map((item) => { const stock = item.available ?? 0; const reserved = item.reserved ?? 0; const onHand = item.on_hand ?? stock + reserved; return <tr key={`${item.product_id}-${item.product?.name}`}><td><span className="customer"><span className="product-avatar"><Package size={16} /></span><b>{item.product?.name ?? `منتج #${item.product_id}`}</b></span></td><td><b className={stock <= 5 ? 'warning-text' : ''}>{stock}</b></td><td className="muted">{reserved}</td><td>{onHand}</td><td><span className={`status ${stock <= 5 ? 'status-قيد-التجهيز' : 'status-تم-الشحن'}`}><i />{stock <= 5 ? 'منخفض' : 'متوفر'}</span></td><td><button className="outline-button small-button" onClick={() => setSelected(item)}><Plus size={14} /> تعديل الكمية</button></td></tr> })}</tbody></table>}</div><div className="table-footer"><span className="muted">عرض {visible.length} من {items.length} صنف</span></div></section>{selected && <StockModal item={selected} onClose={() => setSelected(null)} onAdjust={adjust} />}</div>
}
function SkeletonRows() { return <div className="skeleton-table">{[1, 2, 3, 4, 5].map((row) => <div className="skeleton-row" key={row}><span /><span /><span /><span /></div>)}</div> }
function StockModal({ item, onClose, onAdjust }: { item: ApiInventory; onClose: () => void; onAdjust: (quantity: number) => void }) { const [quantity, setQuantity] = useState(1); return <div className="modal-backdrop" onClick={onClose}><div className="confirm-modal stock-modal" onClick={(event) => event.stopPropagation()}><div className="product-avatar large"><Package size={21} /></div><h2>تعديل المخزون</h2><p>{item.product?.name ?? `منتج #${item.product_id}`} · المتاح حالياً <b>{item.available ?? 0}</b></p><div className="quantity-control"><button onClick={() => setQuantity((value) => Math.max(1, value - 1))}><Minus size={16} /></button><strong>{quantity}</strong><button onClick={() => setQuantity((value) => value + 1)}><Plus size={16} /></button></div><div className="modal-actions"><button className="outline-button" onClick={onClose}>إلغاء</button><button className="primary-button" onClick={() => onAdjust(quantity)}>إضافة</button><button className="danger-button" onClick={() => onAdjust(-quantity)}>خصم</button></div></div></div> }
