import { useEffect, useMemo, useState } from 'react'
import { PageStats } from '../components/PageStats'
import { AlertTriangle, Boxes, Minus, Package, Plus, Search } from 'lucide-react'
import { ApiError, adjustInventory, listInventory, releaseInventory, reserveInventory } from '../lib/api'
import type { ApiInventory } from '../lib/api'

type Props = { onToast: (message: string, type?: 'success' | 'error') => void; access?: { roles?: string[]; permissions?: string[] } }
export function InventoryPage({ onToast, access }: Props) {
  const isAdmin = (access?.roles ?? []).some((role) => ['owner', 'admin'].includes(role))
  const canManage = isAdmin || (access?.permissions ?? []).includes('inventory.manage')
  const [items, setItems] = useState<ApiInventory[]>([])
  const [query, setQuery] = useState('')
  const [stockFilter, setStockFilter] = useState<'all' | 'low' | 'out'>('all')
  const [loading, setLoading] = useState(true)
  const [selected, setSelected] = useState<ApiInventory | null>(null)
  const load = () => { setLoading(true); listInventory().then(setItems).catch((error: unknown) => onToast(error instanceof ApiError ? error.message : 'تعذر تحميل المخزون', 'error')).finally(() => setLoading(false)) }
  // The initial fetch synchronizes the screen with the external Laravel API.
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { load() }, [])
  const visible = useMemo(() => items.filter((item) => { const name = item.product?.name ?? `منتج #${item.product_id}`; const available = item.available ?? 0; return name.toLowerCase().includes(query.toLowerCase()) && (stockFilter === 'all' || (stockFilter === 'low' && available > 0 && available <= 5) || (stockFilter === 'out' && available <= 0)) }), [items, query, stockFilter])
  const adjust = async (quantity: number) => { if (!selected) return; try { await adjustInventory({ product_id: selected.product_id, variant_id: selected.variant_id ?? undefined, quantity, reason: quantity > 0 ? 'purchase' : 'loss', note: 'تعديل من لوحة الإدارة' }); onToast('تم تحديث المخزون'); setSelected(null); load() } catch (error) { onToast(error instanceof ApiError ? error.message : 'تعذر تعديل المخزون', 'error') } }
  const reserve = async (quantity: number, release = false) => { if (!selected) return; try { const payload = { product_id: selected.product_id, variant_id: selected.variant_id ?? undefined, quantity, note: 'تحديث من لوحة الإدارة' }; if (release) await releaseInventory(payload); else await reserveInventory(payload); onToast(release ? 'تم تحرير الحجز' : 'تم حجز الكمية'); setSelected(null); load() } catch (error) { onToast(error instanceof ApiError ? error.message : 'تعذر تحديث الحجز', 'error') } }
  const available = items.reduce((sum, item) => sum + (item.available ?? 0), 0)
  const low = items.filter((item) => (item.available ?? 0) <= 5).length
  return <div className="screen-page"><div className="screen-header"><div><p className="eyebrow">العمليات</p><h1>المخزون</h1><p className="muted">راقب الكمية المتاحة والمحجوزة وعدّل المخزون بأمان.</p></div><div className="inventory-summary"><span><b>{available}</b> وحدة متاحة</span><span className={low ? 'warning-text' : ''}><b>{low}</b> منخفض المخزون</span></div></div><PageStats items={[{ label: 'إجمالي الأصناف', value: loading ? '...' : items.length }, { label: 'منخفض المخزون', value: loading ? '...' : low }, { label: 'الوحدات المتاحة', value: loading ? '...' : available }, { label: 'آخر تحديث', value: loading ? '...' : 'مباشر' }]} /><div className="screen-toolbar"><label className="screen-search"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ابحث عن منتج..." /></label><button className={`filter-chip ${stockFilter === 'low' ? 'selected' : ''}`} onClick={() => setStockFilter(stockFilter === 'low' ? 'all' : 'low')}><AlertTriangle size={13} /> منخفض المخزون</button><button className={`filter-chip ${stockFilter === 'out' ? 'selected' : ''}`} onClick={() => setStockFilter(stockFilter === 'out' ? 'all' : 'out')}><Boxes size={13} /> نافد</button></div><section className="data-card"><div className="table-wrap">{loading ? <SkeletonRows /> : visible.length === 0 ? <div className="empty-state"><Boxes size={28} /><b>لا توجد عناصر مخزون</b><span>لا توجد نتائج مطابقة.</span></div> : <table><thead><tr><th>المنتج</th><th>المتاح</th><th>المحجوز</th><th>الإجمالي</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{visible.map((item) => { const stock = item.available ?? 0; const reserved = item.reserved ?? 0; const onHand = item.on_hand ?? stock + reserved; return <tr key={`${item.product_id}-${item.product?.name}`}><td><span className="customer"><span className="product-avatar"><Package size={16} /></span><b>{item.product?.name ?? `منتج #${item.product_id}`}</b></span></td><td><b className={stock <= 5 ? 'warning-text' : ''}>{stock}</b></td><td className="muted">{reserved}</td><td>{onHand}</td><td><span className={`status ${stock <= 5 ? 'status-قيد-التجهيز' : 'status-تم-الشحن'}`}><i />{stock <= 5 ? 'منخفض' : 'متوفر'}</span></td><td>{canManage && <button className="outline-button small-button" onClick={() => setSelected(item)}><Plus size={14} /> تعديل الكمية</button>}</td></tr> })}</tbody></table>}</div><div className="table-footer"><span className="muted">عرض {visible.length} من {items.length} صنف</span></div></section>{selected && <StockModal item={selected} onClose={() => setSelected(null)} onAdjust={adjust} onReserve={(quantity) => reserve(quantity)} onRelease={(quantity) => reserve(quantity, true)} />}</div>
}
function SkeletonRows() { return <div className="skeleton-table">{[1, 2, 3, 4, 5].map((row) => <div className="skeleton-row" key={row}><span /><span /><span /><span /></div>)}</div> }
function StockModal({ item, onClose, onAdjust, onReserve, onRelease }: { item: ApiInventory; onClose: () => void; onAdjust: (quantity: number) => void; onReserve: (quantity: number) => void; onRelease: (quantity: number) => void }) { const [quantity, setQuantity] = useState(1); const safeQuantity = Math.max(1, Math.floor(quantity || 1)); return <div className="modal-backdrop" onClick={onClose}><div className="confirm-modal stock-modal" onClick={(event) => event.stopPropagation()}><div className="product-avatar large"><Package size={21} /></div><h2>تعديل المخزون</h2><p>{item.product?.name ?? `منتج #${item.product_id}`} · المتاح حالياً <b>{item.available ?? 0}</b></p>{(item.movements ?? []).length > 0 && <div className="movement-history"><h3>آخر الحركات</h3>{(item.movements ?? []).map((movement) => <div className="movement-row" key={movement.id}><span className={movement.quantity >= 0 ? 'positive' : 'negative'}>{movement.quantity > 0 ? '+' : ''}{movement.quantity}</span><span>{movement.reason ?? 'تعديل'}</span><small>{movement.actor?.name ?? 'النظام'} · {movement.created_at ? new Date(movement.created_at).toLocaleString('ar-EG') : ''}</small></div>)}</div>}<div className="quantity-control"><button onClick={() => setQuantity((value) => Math.max(1, value - 1))}><Minus size={16} /></button><input className="quantity-input" type="number" min="1" value={quantity} onChange={(event) => setQuantity(Math.max(1, Number(event.target.value) || 1))} aria-label="الكمية" /><button onClick={() => setQuantity((value) => value + 1)}><Plus size={16} /></button></div><div className="modal-actions"><button className="outline-button" onClick={onClose}>إلغاء</button><button className="primary-button" onClick={() => onAdjust(safeQuantity)}>إضافة</button><button className="danger-button" onClick={() => onAdjust(-safeQuantity)}>خصم</button><button className="outline-button" onClick={() => onReserve(safeQuantity)}>حجز</button><button className="outline-button" onClick={() => onRelease(safeQuantity)}>تحرير الحجز</button></div></div></div> }
