import { useEffect, useState } from 'react'
import { Check, Gift, MessageSquare, Plus, Shield, Trash2, UserRound, X } from 'lucide-react'
import { ApiError, createCoupon, createStaff, deleteCoupon, deleteStaff, listCoupons, listReviews, listReturns, listStaff, moderateReview, updateReturn } from '../lib/api'

type Props = { onToast: (message: string, type?: 'success' | 'error') => void }
type Tab = 'staff' | 'coupons' | 'returns' | 'reviews'
type Row = Record<string, unknown>
const text = (value: unknown, fallback = '—') => value === null || value === undefined || value === '' ? fallback : String(value)
export function ManagementPage({ onToast }: Props) {
  const [tab, setTab] = useState<Tab>('staff')
  const [rows, setRows] = useState<Row[]>([])
  const [loading, setLoading] = useState(true)
  const [formOpen, setFormOpen] = useState(false)
  const [form, setForm] = useState<Record<string, string>>({})
  const load = async () => { setLoading(true); try { const data = tab === 'staff' ? await listStaff() : tab === 'coupons' ? await listCoupons() : tab === 'returns' ? await listReturns() : await listReviews(); setRows(data) } catch (error) { onToast(error instanceof ApiError ? error.message : 'تعذر تحميل البيانات', 'error') } finally { setLoading(false) } }
  // Synchronize each management tab with its external Laravel API resource.
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { void load() }, [tab])
  const submit = async (event: React.FormEvent) => { event.preventDefault(); try { if (tab === 'staff') await createStaff({ name: form.name, email: form.email, password: form.password, password_confirmation: form.password, status: 'active', roles: ['support_agent'] }); else await createCoupon({ code: form.code, type: form.type || 'percent', value: Number(form.value), is_active: true }); onToast('تم الإنشاء بنجاح'); setFormOpen(false); setForm({}); load() } catch (error) { onToast(error instanceof ApiError ? error.message : 'تعذر إنشاء السجل', 'error') } }
  const remove = async (row: Row) => { try { if (tab === 'staff') await deleteStaff(Number(row.id)); else await deleteCoupon(Number(row.id)); onToast('تم الحذف'); load() } catch (error) { onToast(error instanceof ApiError ? error.message : 'تعذر الحذف', 'error') } }
  const action = async (row: Row, type: string) => { try { if (tab === 'returns') await updateReturn(Number(row.id), type as 'approve' | 'receive' | 'reject', type === 'reject' ? { reason: 'تم الرفض من لوحة الإدارة' } : {}); else await moderateReview(Number(row.id), type); onToast('تم تحديث الحالة'); load() } catch (error) { onToast(error instanceof ApiError ? error.message : 'تعذر تحديث الحالة', 'error') } }
  const tabs: Array<[Tab, string, typeof UserRound]> = [['staff', 'الموظفون', UserRound], ['coupons', 'القسائم', Gift], ['returns', 'الإرجاعات', Shield], ['reviews', 'المراجعات', MessageSquare]]
  return <div className="screen-page"><div className="screen-header"><div><p className="eyebrow">الإدارة</p><h1>إدارة المتجر</h1><p className="muted">الموظفون، القسائم، الإرجاعات ومراجعات العملاء.</p></div>{(tab === 'staff' || tab === 'coupons') && <button className="primary-button" onClick={() => { setForm({}); setFormOpen(true) }}><Plus size={16} /> إضافة {tab === 'staff' ? 'موظف' : 'قسيمة'}</button>}</div><div className="management-tabs">{tabs.map(([value, label, Icon]) => <button key={value} className={tab === value ? 'active' : ''} onClick={() => setTab(value)}><Icon size={16} />{label}</button>)}</div><section className="data-card"><div className="table-wrap">{loading ? <div className="settings-loading">جار التحميل...</div> : rows.length === 0 ? <div className="empty-state"><Shield size={28} /><b>لا توجد سجلات</b><span>لا توجد بيانات متاحة من الـAPI لهذا القسم.</span></div> : <table><thead><tr>{tab === 'staff' ? <><th>الاسم</th><th>البريد</th><th>الحالة</th><th>إجراء</th></> : tab === 'coupons' ? <><th>الكود</th><th>النوع</th><th>القيمة</th><th>إجراء</th></> : tab === 'returns' ? <><th>الطلب</th><th>السبب</th><th>الحالة</th><th>إجراء</th></> : <><th>المنتج</th><th>التقييم</th><th>الحالة</th><th>إجراء</th></>}</tr></thead><tbody>{rows.map((row) => <tr key={String(row.id)}>{tab === 'staff' ? <><td><b>{text(row.name)}</b></td><td className="muted">{text(row.email, text(row.phone))}</td><td><span className="status status-تم-الشحن"><i />{text(row.status, 'active')}</span></td><td><button className="quick-action danger" onClick={() => void remove(row)}><Trash2 size={15} /></button></td></> : tab === 'coupons' ? <><td><b className="order-id">{text(row.code)}</b></td><td>{text(row.type)}</td><td>{text(row.value)}</td><td><button className="quick-action danger" onClick={() => void remove(row)}><Trash2 size={15} /></button></td></> : tab === 'returns' ? <><td><b>{text(row.order_number, text(row.order_id))}</b></td><td className="muted">{text(row.reason)}</td><td>{text(row.status)}</td><td><div className="quick-actions"><button title="موافقة" onClick={() => void action(row, 'approve')}><Check size={15} /></button><button title="رفض" className="danger" onClick={() => void action(row, 'reject')}><X size={15} /></button></div></td></> : <><td><b>{text(row.product_name, text(row.product_id))}</b></td><td>{text(row.rating)} / 5</td><td>{text(row.status)}</td><td><div className="quick-actions"><button title="اعتماد" onClick={() => void action(row, 'approved')}><Check size={15} /></button><button title="رفض" className="danger" onClick={() => void action(row, 'rejected')}><X size={15} /></button></div></td></>}</tr>)}</tbody></table>}</div></section>{formOpen && <ManagementForm tab={tab} form={form} setForm={setForm} onClose={() => setFormOpen(false)} onSubmit={submit} />}</div>
}
function ManagementForm({ tab, form, setForm, onClose, onSubmit }: { tab: Tab; form: Record<string, string>; setForm: (value: Record<string, string>) => void; onClose: () => void; onSubmit: (event: React.FormEvent) => void }) { const update = (key: string, value: string) => setForm({ ...form, [key]: value }); return <div className="modal-backdrop" onClick={onClose}><div className="form-modal" onClick={(event) => event.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">الإدارة</span><h2>إضافة {tab === 'staff' ? 'موظف' : 'قسيمة'}</h2></div><button className="icon-button" onClick={onClose}>×</button></div><form onSubmit={onSubmit}>{tab === 'staff' ? <><label className="form-field"><span>الاسم</span><input required value={form.name ?? ''} onChange={(event) => update('name', event.target.value)} /></label><label className="form-field"><span>البريد الإلكتروني</span><input type="email" required value={form.email ?? ''} onChange={(event) => update('email', event.target.value)} /></label><label className="form-field"><span>كلمة المرور</span><input type="password" required minLength={8} value={form.password ?? ''} onChange={(event) => update('password', event.target.value)} /></label></> : <><label className="form-field"><span>كود القسيمة</span><input required value={form.code ?? ''} onChange={(event) => update('code', event.target.value.toUpperCase())} /></label><label className="form-field"><span>النوع</span><select value={form.type ?? 'percent'} onChange={(event) => update('type', event.target.value)}><option value="percent">نسبة مئوية</option><option value="fixed">قيمة ثابتة</option></select></label><label className="form-field"><span>القيمة</span><input required type="number" min="1" value={form.value ?? ''} onChange={(event) => update('value', event.target.value)} /></label></>}<div className="modal-actions"><button type="button" className="outline-button" onClick={onClose}>إلغاء</button><button className="primary-button">حفظ</button></div></form></div></div> }
