import { useEffect, useState } from 'react'
import { AlertTriangle, Check, Play, ShieldCheck } from 'lucide-react'
import { ApiError, acknowledgeOperationalAlert, listDelayedOrders, listOperationalAlerts, resolveOperationalAlert, runDelayedOrderDetection } from '../lib/api'
type Props = { onToast: (message: string, type?: 'success' | 'error') => void }
type Tab = 'delayed' | 'alerts'
type Row = Record<string, unknown>
const text = (v: unknown, f = '—') => v === null || v === undefined || v === '' ? f : String(v)
const rowsOf = (value: Array<Row> | { data?: Array<Row> }) => Array.isArray(value) ? value : value.data ?? []
export function MonitoringPage({ onToast }: Props) {
  const [tab, setTab] = useState<Tab>('delayed'); const [rows, setRows] = useState<Row[]>([]); const [status, setStatus] = useState(''); const [loading, setLoading] = useState(true); const [running, setRunning] = useState(false)
  const load = async () => { setLoading(true); try { const result = tab === 'delayed' ? await listDelayedOrders() : await listOperationalAlerts(status ? { status } : {}); setRows(rowsOf(result)) } catch (error) { onToast(error instanceof ApiError ? error.message : 'تعذر تحميل بيانات المراقبة', 'error') } finally { setLoading(false) } }
  // Synchronize the monitoring tab and status filter with the Laravel API.
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { void load() }, [tab, status])
  const detect = async () => { setRunning(true); try { await runDelayedOrderDetection(); onToast('تم تشغيل فحص الطلبات المتأخرة'); load() } catch (error) { onToast(error instanceof ApiError ? error.message : 'تعذر تشغيل الفحص', 'error') } finally { setRunning(false) } }
  const action = async (row: Row, type: 'acknowledge' | 'resolve') => { try { if (type === 'acknowledge') await acknowledgeOperationalAlert(Number(row.id)); else await resolveOperationalAlert(Number(row.id)); onToast(type === 'acknowledge' ? 'تم تأكيد التنبيه' : 'تم حل التنبيه'); load() } catch (error) { onToast(error instanceof ApiError ? error.message : 'تعذر تحديث التنبيه', 'error') } }
  return <div className="screen-page"><div className="screen-header"><div><p className="eyebrow">المراقبة التشغيلية</p><h1>المتابعة والتنبيهات</h1><p className="muted">اكتشف الطلبات المتأخرة وتعامل مع التنبيهات التشغيلية من مكان واحد.</p></div><button className="primary-button" disabled={running} onClick={() => void detect()}><Play size={15} />{running ? 'جار الفحص...' : 'تشغيل الفحص'}</button></div><div className="management-tabs"><button className={tab === 'delayed' ? 'active' : ''} onClick={() => setTab('delayed')}><AlertTriangle size={16} /> الطلبات المتأخرة</button><button className={tab === 'alerts' ? 'active' : ''} onClick={() => setTab('alerts')}><ShieldCheck size={16} /> التنبيهات</button></div>{tab === 'alerts' && <div className="filter-bar"><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">كل الحالات</option><option value="open">مفتوح</option><option value="acknowledged">تم التأكيد</option><option value="resolved">تم الحل</option></select></div>}<section className="data-card"><div className="table-wrap">{loading ? <div className="settings-loading">جار التحميل...</div> : rows.length === 0 ? <div className="empty-state"><ShieldCheck size={28} /><b>لا توجد سجلات</b><span>كل العمليات تبدو مستقرة حاليًا.</span></div> : tab === 'delayed' ? <table><thead><tr><th>الطلب</th><th>النوع</th><th>الحالة</th><th>مدة التأخير</th><th>العميل</th></tr></thead><tbody>{rows.map((row) => <tr key={String(row.id)}><td><b>{text(row.order_number, text(row.order_id))}</b></td><td>{text(row.delay_type, text(row.type))}</td><td>{text(row.status)}</td><td className="warning-text">{text(row.delayed_days, text(row.days))} يوم</td><td>{text(row.customer_name, text((row.customer as Record<string, unknown> | undefined)?.name))}</td></tr>)}</tbody></table> : <table><thead><tr><th>العنوان</th><th>النوع</th><th>الخطورة</th><th>الحالة</th><th>التاريخ</th><th>إجراء</th></tr></thead><tbody>{rows.map((row) => { const current = text(row.status, 'open'); return <tr key={String(row.id)}><td><b>{text(row.title, text(row.message))}</b></td><td>{text(row.type, text(row.alert_type))}</td><td>{text(row.severity)}</td><td>{current}</td><td>{text(row.created_at)}</td><td><div className="quick-actions">{current === 'open' && <button title="تأكيد" onClick={() => void action(row, 'acknowledge')}><Check size={15} /></button>}{current !== 'resolved' && <button title="حل" className="danger" onClick={() => void action(row, 'resolve')}><ShieldCheck size={15} /></button>}</div></td></tr>})}</tbody></table>}</div></section></div>
}
