import { useEffect, useState } from 'react'
import { CheckCircle2, RefreshCw, Search, Truck } from 'lucide-react'
import { ApiError, listShipments, updateShipmentStatus } from '../lib/api'
import { PageStats } from '../components/PageStats'

type Row = Record<string, unknown> & { id?: number | string; status?: string; tracking_number?: string; provider_code?: string; order_id?: number | string; updated_at?: string; user?: { name?: string; email?: string }; order?: { order_number?: string | number }; method?: { carrier?: string } }
type Props = { onToast: (message: string, type?: 'success' | 'error') => void; access?: { roles?: string[]; permissions?: string[] } }
const labels: Record<string, string> = { processing: 'قيد الإنشاء', provider_created: 'تم الإنشاء', picked_up: 'تم الاستلام', in_transit: 'في الطريق', out_for_delivery: 'خرج للتسليم', delivered: 'تم التسليم', failed: 'فشل', ambiguous: 'تحتاج مراجعة', cancelled: 'ملغاة' }
const nextStatus: Record<string, string> = { provider_created: 'picked_up', picked_up: 'in_transit', in_transit: 'out_for_delivery', out_for_delivery: 'delivered' }
const text = (value: unknown, fallback = '—') => value === null || value === undefined || value === '' ? fallback : String(value)

export function ShipmentsPage({ onToast, access }: Props) {
  const admin = (access?.roles ?? []).some((role) => ['owner', 'admin'].includes(role))
  const canManage = admin || (access?.permissions ?? []).includes('shipping.manage')
  const [rows, setRows] = useState<Row[]>([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [meta, setMeta] = useState({ total: 0 })
  const load = async () => { setLoading(true); try { const result = await listShipments({ per_page: 25, ...(search ? { search } : {}), ...(status ? { status } : {}) }); setRows((result.data ?? []) as Row[]); setMeta({ total: Number(result.meta?.total ?? result.data?.length ?? 0) }) } catch (error) { onToast(error instanceof ApiError ? error.message : 'تعذر تحميل الشحنات', 'error') } finally { setLoading(false) } }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { const timer = window.setTimeout(() => void load(), 250); return () => window.clearTimeout(timer) }, [search, status])
  const advance = async (row: Row) => { const next = nextStatus[text(row.status)]; if (!next) return onToast('لا يوجد انتقال آمن لهذه الحالة', 'error'); try { const updated = await updateShipmentStatus(Number(row.id), next); setRows((current) => current.map((item) => item.id === row.id ? updated as Row : item)); onToast('تم تحديث حالة الشحنة') } catch (error) { onToast(error instanceof ApiError ? error.message : 'تعذر تحديث الشحنة', 'error') } }
  return <div className="screen-page"><div className="screen-header"><div><p className="eyebrow">اللوجستيات</p><h1>الشحنات</h1><p className="muted">تابع الشحنات والاستثناءات وحالة التسليم من مكان واحد.</p></div><button className="outline-button" onClick={() => void load()}><RefreshCw size={16} /> تحديث</button></div><PageStats items={[{ label: 'إجمالي الشحنات', value: loading ? '...' : meta.total }, { label: 'في الصفحة', value: loading ? '...' : rows.length }, { label: 'تحتاج مراجعة', value: loading ? '...' : rows.filter((row) => ['failed', 'ambiguous'].includes(text(row.status))).length }, { label: 'تم التسليم', value: loading ? '...' : rows.filter((row) => text(row.status) === 'delivered').length }]} /><div className="screen-toolbar"><label className="screen-search"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="ابحث برقم الطلب أو التتبع أو العميل..." /></label><select className="filter-select-control" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">كل الحالات</option>{Object.entries(labels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div><section className="data-card"><div className="table-wrap">{loading ? <div className="settings-loading">جار تحميل الشحنات...</div> : rows.length === 0 ? <div className="empty-state"><Truck size={28} /><b>لا توجد شحنات</b><span>ستظهر الشحنات هنا عند إنشائها.</span></div> : <table><thead><tr><th>الشحنة</th><th>الطلب</th><th>العميل</th><th>الناقل</th><th>التتبع</th><th>الحالة</th><th>آخر تحديث</th><th>إجراء</th></tr></thead><tbody>{rows.map((row) => <tr key={String(row.id)}><td><b>#{text(row.id)}</b></td><td className="order-id">#{text(row.order?.order_number, text(row.order_id))}</td><td>{text(row.user?.name, text(row.user?.email, 'عميل'))}</td><td>{text(row.method?.carrier, text(row.provider_code))}</td><td className="tabular">{text(row.tracking_number)}</td><td><span className={`status status-${text(row.status)}`}><i />{labels[text(row.status)] ?? text(row.status)}</span></td><td className="muted">{row.updated_at ? new Date(row.updated_at).toLocaleString('ar-EG') : '—'}</td><td>{canManage && nextStatus[text(row.status)] ? <button className="quick-action" title="تحديث للحالة التالية" onClick={() => void advance(row)}><CheckCircle2 size={16} /></button> : <span className="muted">—</span>}</td></tr>)}</tbody></table>}</div></section></div>
}
