"use client";

import { useState } from "react";

const inputClass = "h-11 w-full rounded-lg border border-[#dfe7df] bg-white px-3 text-sm outline-none transition focus:border-[#8daf60] focus:ring-2 focus:ring-[#d7f26b]/30";

export function CouponForm() {
  const [saved, setSaved] = useState(false);
  return <form onSubmit={(event) => { event.preventDefault(); setSaved(true); }} className="rounded-2xl border border-[#e1e9e1] bg-white p-6"><div className="grid gap-5 md:grid-cols-2"><label className="block"><span className="mb-2 block text-xs font-semibold text-[#52655a]">Coupon code</span><input required placeholder="e.g. WELCOME10" className={inputClass} /></label><label className="block"><span className="mb-2 block text-xs font-semibold text-[#52655a]">Discount type</span><select className={inputClass}><option>Percentage</option><option>Fixed amount</option><option>Free shipping</option></select></label><label className="block"><span className="mb-2 block text-xs font-semibold text-[#52655a]">Discount value</span><input required type="number" placeholder="10" className={inputClass} /></label><label className="block"><span className="mb-2 block text-xs font-semibold text-[#52655a]">Usage limit</span><input type="number" placeholder="Unlimited" className={inputClass} /></label><label className="block"><span className="mb-2 block text-xs font-semibold text-[#52655a]">Start date</span><input type="date" className={inputClass} /></label><label className="block"><span className="mb-2 block text-xs font-semibold text-[#52655a]">End date</span><input type="date" className={inputClass} /></label></div><div className="mt-6 flex items-center justify-end gap-3"><button type="button" className="rounded-lg border border-[#dfe7df] px-4 py-2.5 text-xs font-bold text-[#52655a]">Cancel</button><button type="submit" className="rounded-lg bg-[#173b2d] px-5 py-2.5 text-xs font-bold text-white">{saved ? "Coupon saved ✓" : "Create coupon"}</button></div></form>;
}

export function SettingsPanel() {
  const [saved, setSaved] = useState(false);
  return <form onSubmit={(event) => { event.preventDefault(); setSaved(true); }} className="grid gap-5 lg:grid-cols-[220px_1fr]"><nav className="flex gap-2 overflow-x-auto lg:block lg:space-y-1">{["General", "Store", "Payments", "Shipping", "Notifications"].map((item, index) => <button type="button" key={item} className={`whitespace-nowrap rounded-lg px-3 py-2.5 text-left text-xs font-semibold lg:block lg:w-full ${index === 0 ? "bg-[#e8f2df] text-[#608428]" : "text-[#809087] hover:bg-white"}`}>{item}</button>)}</nav><div className="rounded-2xl border border-[#e1e9e1] bg-white p-6"><h3 className="font-bold">General settings</h3><p className="mt-1 text-xs text-[#8b9991]">Manage the identity and defaults for your store.</p><div className="mt-6 grid gap-5 md:grid-cols-2"><label className="block"><span className="mb-2 block text-xs font-semibold text-[#52655a]">Store name</span><input defaultValue="Northstar" className={inputClass} /></label><label className="block"><span className="mb-2 block text-xs font-semibold text-[#52655a]">Support email</span><input type="email" defaultValue="hello@northstar.com" className={inputClass} /></label><label className="block md:col-span-2"><span className="mb-2 block text-xs font-semibold text-[#52655a]">Store description</span><textarea rows={4} defaultValue="Thoughtful everyday goods, designed to last." className="w-full resize-none rounded-lg border border-[#dfe7df] px-3 py-3 text-sm outline-none focus:border-[#8daf60]" /></label></div><div className="mt-6 flex justify-end"><button className="rounded-lg bg-[#173b2d] px-5 py-2.5 text-xs font-bold text-white">{saved ? "Changes saved ✓" : "Save changes"}</button></div></div></form>;
}

export function StockAdjuster() {
  const [stock, setStock] = useState(124);
  return <div className="rounded-2xl border border-[#e1e9e1] bg-white p-6"><div className="flex items-center justify-between"><div><h3 className="font-bold">Quick stock adjustment</h3><p className="mt-1 text-xs text-[#8b9991]">Update inventory without leaving this view.</p></div><span className="rounded-full bg-[#edf7dc] px-2.5 py-1 text-[10px] font-bold text-[#608428]">Live preview</span></div><div className="mt-6 flex flex-col gap-3 sm:flex-row"><select className={inputClass}><option>Minimal leather wallet · WL-2048</option><option>Everyday canvas tote · BG-3321</option></select><input value={stock} onChange={(event) => setStock(Number(event.target.value))} type="number" className={`${inputClass} sm:max-w-32`} /><button className="rounded-lg bg-[#173b2d] px-5 py-2.5 text-xs font-bold text-white">Save stock</button></div></div>;
}

export function InviteUserForm() {
  const [invited, setInvited] = useState(false);
  return <form onSubmit={(event) => { event.preventDefault(); setInvited(true); }} className="rounded-2xl border border-[#e1e9e1] bg-white p-6"><div className="grid gap-5 md:grid-cols-2"><label className="block"><span className="mb-2 block text-xs font-semibold text-[#52655a]">Full name</span><input required placeholder="e.g. Mia Chen" className={inputClass} /></label><label className="block"><span className="mb-2 block text-xs font-semibold text-[#52655a]">Email address</span><input required type="email" placeholder="mia@northstar.com" className={inputClass} /></label><label className="block"><span className="mb-2 block text-xs font-semibold text-[#52655a]">Role</span><select className={inputClass}><option>Catalog manager</option><option>Administrator</option><option>Support agent</option></select></label></div><div className="mt-6 flex justify-end"><button className="rounded-lg bg-[#173b2d] px-5 py-2.5 text-xs font-bold text-white">{invited ? "Invitation sent ✓" : "Send invitation"}</button></div></form>;
}
