"use client";

import { useState } from "react";

export function ProductForm({ mode = "create" }: { mode?: "create" | "edit" }) {
  const [saved, setSaved] = useState(false);
  return <form onSubmit={(event) => { event.preventDefault(); setSaved(true); }} className="space-y-5"><div className="grid gap-5 lg:grid-cols-[1fr_320px]"><div className="space-y-5"><section className="rounded-2xl border border-[#e1e9e1] bg-white p-6"><h3 className="font-bold">Basic information</h3><p className="mt-1 text-xs text-[#8b9991]">The essential details customers see first.</p><div className="mt-6 space-y-5"><Field label="Product name" defaultValue={mode === "edit" ? "Minimal leather wallet" : ""} placeholder="e.g. Minimal leather wallet" /><Field label="Description" placeholder="Describe your product..." textarea /><div className="grid gap-5 sm:grid-cols-2"><Field label="SKU" defaultValue={mode === "edit" ? "WL-2048" : ""} placeholder="WL-0000" /><label className="block"><span className="mb-2 block text-xs font-semibold text-[#52655a]">Category</span><select className="h-11 w-full rounded-lg border border-[#dfe7df] bg-white px-3 text-sm text-[#52655a] outline-none focus:border-[#8daf60]"><option>Accessories</option><option>Apparel</option><option>Bags</option><option>Home</option></select></label></div></div></section><section className="rounded-2xl border border-[#e1e9e1] bg-white p-6"><h3 className="font-bold">Pricing & inventory</h3><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Price" defaultValue={mode === "edit" ? "48.00" : ""} placeholder="0.00" prefix="$" /><Field label="Stock quantity" defaultValue={mode === "edit" ? "124" : ""} placeholder="0" /></div></section></div><aside className="space-y-5"><section className="rounded-2xl border border-[#e1e9e1] bg-white p-6"><h3 className="font-bold">Product status</h3><div className="mt-5 space-y-3"><label className="flex items-center gap-3 rounded-lg border border-[#dfe7df] p-3 text-xs"><input type="radio" name="status" defaultChecked /> <span><b className="block">Active</b><span className="text-[#8b9991]">Visible in your storefront</span></span></label><label className="flex items-center gap-3 rounded-lg border border-[#dfe7df] p-3 text-xs"><input type="radio" name="status" /> <span><b className="block">Draft</b><span className="text-[#8b9991]">Only visible to your team</span></span></label></div></section><div className="rounded-2xl bg-[#173b2d] p-6 text-white"><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#d7f26b]">Next step</p><p className="mt-3 text-sm leading-6 text-white/60">You can add variants, images, and SEO details after saving.</p></div></aside></div><div className="flex items-center justify-end gap-3"><button type="button" className="rounded-lg border border-[#dfe7df] bg-white px-4 py-2.5 text-xs font-bold text-[#52655a]">Cancel</button><button type="submit" className="rounded-lg bg-[#173b2d] px-5 py-2.5 text-xs font-bold text-white">{saved ? "Saved ✓" : mode === "edit" ? "Save changes" : "Create product"}</button></div></form>;
}

function Field({ label, placeholder, defaultValue, textarea, prefix }: { label: string; placeholder?: string; defaultValue?: string; textarea?: boolean; prefix?: string }) { return <label className="block"><span className="mb-2 block text-xs font-semibold text-[#52655a]">{label}</span><div className="relative">{prefix && <span className="absolute left-3 top-3 text-sm text-[#8b9991]">{prefix}</span>}{textarea ? <textarea rows={4} placeholder={placeholder} className="w-full resize-none rounded-lg border border-[#dfe7df] px-3 py-3 text-sm outline-none placeholder:text-[#b0bbb4] focus:border-[#8daf60]" /> : <input defaultValue={defaultValue} placeholder={placeholder} className={`h-11 w-full rounded-lg border border-[#dfe7df] px-3 text-sm outline-none placeholder:text-[#b0bbb4] focus:border-[#8daf60] ${prefix ? "pl-7" : ""}`} />}</div></label>; }
