"use client";

import { useState } from "react";
import Link from "next/link";
import { Sidebar } from "./sidebar";

export function DashboardShell({ children }: { children: React.ReactNode }) {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  return <div className="flex min-h-screen bg-[#f8f9fa] text-[#1e293b]"><Sidebar open={sidebarOpen} onClose={() => setSidebarOpen(false)} /><div className="flex min-w-0 flex-1 flex-col"><header className="flex h-[68px] items-center justify-between border-b border-[#e8edf1] bg-white/95 px-4 backdrop-blur sm:h-[82px] sm:px-5 lg:px-10"><div className="flex items-center gap-3"><button onClick={() => setSidebarOpen(true)} aria-label="Open navigation" className="grid size-9 place-items-center rounded-lg border border-[#e5eaf0] text-lg lg:hidden">☰</button><div><p className="hidden text-[11px] font-medium text-[#94a3b8] sm:block">Monday, September 14, 2026</p><h1 className="text-[15px] font-bold tracking-[-0.02em] sm:text-lg">Good morning, Alex <span aria-hidden="true">✦</span></h1></div></div><div className="flex items-center gap-1.5 sm:gap-2"><button className="grid size-8 place-items-center rounded-lg border border-[#e5eaf0] bg-white text-sm text-[#64748b] sm:size-9" aria-label="Search">⌕</button><button className="relative grid size-8 place-items-center rounded-lg border border-[#e5eaf0] bg-white text-sm text-[#64748b] sm:size-9" aria-label="Notifications">♢<span className="absolute right-1.5 top-1.5 size-1.5 rounded-full bg-[#e36b4d]" /></button><div className="ml-1 hidden h-7 w-px bg-[#e5eaf0] sm:block" /><div className="hidden items-center gap-2 sm:flex"><div className="grid size-8 place-items-center rounded-full bg-[#e6b99b] text-[10px] font-bold">AM</div><span className="text-xs font-semibold">Alex Morgan</span></div></div></header><main className="flex-1 px-4 pb-24 pt-5 sm:px-5 sm:py-7 lg:px-10 lg:py-9">{children}</main><MobileTabBar /></div></div>;
}

export function Breadcrumbs({ items }: { items: string[] }) { return <div className="mb-7 flex items-center gap-2 text-xs text-[#8b9991]"><span>Dashboard</span>{items.map((item) => <span key={item} className="flex items-center gap-2"><span>/</span><span className="text-[#3f5148]">{item}</span></span>)}</div>; }

function MobileTabBar() { return <nav className="fixed inset-x-0 bottom-0 z-30 grid grid-cols-5 border-t border-[#e8edf1] bg-white/95 px-2 pb-[env(safe-area-inset-bottom)] pt-2 shadow-[0_-8px_24px_rgba(15,23,42,0.06)] backdrop-blur lg:hidden"><Link href="/dashboard" className="flex flex-col items-center gap-1 py-1 text-[10px] font-semibold text-[#608428]"><span className="text-lg">⌂</span>Home</Link><Link href="/orders" className="flex flex-col items-center gap-1 py-1 text-[10px] font-semibold text-[#64748b]"><span className="text-lg">◒</span>Orders</Link><Link href="/products" className="flex flex-col items-center gap-1 py-1 text-[10px] font-semibold text-[#64748b]"><span className="text-lg">▦</span>Catalog</Link><Link href="/customers" className="flex flex-col items-center gap-1 py-1 text-[10px] font-semibold text-[#64748b]"><span className="text-lg">♧</span>Customers</Link><Link href="/settings" className="flex flex-col items-center gap-1 py-1 text-[10px] font-semibold text-[#64748b]"><span className="text-lg">⚙</span>More</Link></nav>; }
